let CourseData = [
  {
    id: 0,
    language: "FR",
    level: "elementary",
    category: "Le français pour les débutants",
    categoryKR: "프랑스어 입문",
    instructor: "R. Gary",
    title: "Le français dans la vie",
    summary:
      "Le français dans la vie : comment s'introduire, parler des jours, des nombres, du temps",
    description: "",
    price: 100,
    main: true,
    hot: true,
    discount: true,
    discountCode: "Early Bird",
    discountRate: 30,
  },
  {
    id: 1,
    language: "FR",
    level: "elementary",
    category: "Grammaire française : niveau élémentaire",
    categoryKR: "프랑스어 문법 (초급)",
    instructor: "R. Gary",
    title:
      "Verbes au présent, les adjectifs, les adverbes, les articles, l'accord en genre et en nombre",
    summary:
      "être, avoir, aller, venir, et faire : les verbes les plus utilisés et les plus essentiels dans la langue française",
    description: "",
    price: 100,
    main: true,
    hot: true,
    discount: true,
    discountCode: "VIP",
    discountRate: 20,
  },
  {
    id: 2,
    language: "FR",
    level: "elementary",
    category: "Compréhension écrite : niveau élémentaire",
    categoryKR: "프랑스어 독해 (초급)",
    instructor: "M. Chagall",
    title: "-",
    summary: "-",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 3,
    language: "FR",
    level: "elementary",
    category: "Compréhension orale : niveau élémentaire",
    categoryKR: "프랑스어 청해 (초급)",
    instructor: "M. Chagall",
    title: "-",
    summary: "-",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 4,
    language: "FR",
    level: "elementary",
    category: "Production orale : niveau élémentaire",
    categoryKR: "프랑스어 회화 (초급)",
    instructor: "M. Chagall",
    title: "-",
    summary: "-",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 5,
    language: "FR",
    level: "elementary",
    category: "Production écrite : niveau élémentaire",
    categoryKR: "프랑스어 작문 (초급)",
    instructor: "M. Chagall",
    title: "-",
    summary: "-",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 6,
    language: "FR",
    level: "elementary",
    category: "Vocabulaire français : niveau élémentaire",
    categoryKR: "프랑스어 어휘 (초급)",
    instructor: "M. Chagall",
    title: "-",
    summary: "-",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 7,
    language: "FR",
    level: "intermediate",
    category: "Grammaire française : niveau intermédiaire",
    categoryKR: "프랑스어 문법 (중급)",
    instructor: "M. Chagall",
    title: "Verbes au passé, au futur, les pronoms relatifs",
    summary: "Le passé composé, l'imparfait, le passif, les pronoms relatifs..",
    description: "",
    price: 100,
    main: true,
    hot: true,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 8,
    language: "FR",
    level: "intermediate",
    category: "Compréhension écrite : niveau intermédiaire",
    categoryKR: "프랑스어 독해 (중급)",
    instructor: "M. Chagall",
    title: "-",
    summary: "-",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 9,
    language: "FR",
    level: "intermediate",
    category: "Compréhension orale : niveau intermédiaire",
    categoryKR: "프랑스어 청해 (중급)",
    instructor: "M. Chagall",
    title: "-",
    summary: "-",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 10,
    language: "FR",
    level: "intermediate",
    category: "Production orale : niveau intermédiaire",
    categoryKR: "프랑스어 회화 (중급)",
    instructor: "M. Chagall",
    title: "-",
    summary: "-",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 11,
    language: "FR",
    level: "intermediate",
    category: "Production écrite : niveau intermédiaire",
    categoryKR: "프랑스어 작문 (중급)",
    instructor: "M. Chagall",
    title: "-",
    summary: "-",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 12,
    language: "FR",
    level: "intermediate",
    category: "Vocabulaire français : niveau intermédiaire",
    categoryKR: "프랑스어 어휘 (중급)",
    instructor: "M. Chagall",
    title: "-",
    summary: "-",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 13,
    language: "FR",
    level: "advanced",
    category: "Grammaire française : niveau avancé",
    categoryKR: "프랑스어 문법 (고급)",
    instructor: "M. Chagall",
    title: "CECR NIVEAU C1/C2",
    summary: "Les conditionnels, les subjonctifs, les suppositifs",
    description: "",
    price: 100,
    main: true,
    hot: true,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 14,
    language: "FR",
    level: "advanced",
    category: "Compréhension écrite : niveau avancé",
    categoryKR: "프랑스어 독해 (고급)",
    instructor: "M. Chagall",
    title: "=",
    summary: "=",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 15,
    language: "FR",
    level: "advanced",
    category: "Compréhension orale : niveau avancé",
    categoryKR: "프랑스어 청해 (고급)",
    instructor: "M. Chagall",
    title: "=",
    summary: "=",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 16,
    language: "FR",
    level: "advanced",
    category: "Production orale : niveau avancé",
    categoryKR: "프랑스어 회화 (고급)",
    instructor: "M. Chagall",
    title: "=",
    summary: "=",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 17,
    language: "FR",
    level: "advanced",
    category: "Production écrite : niveau avancé",
    categoryKR: "프랑스어 작문 (고급)",
    instructor: "M. Chagall",
    title: "=",
    summary: "=",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 18,
    language: "FR",
    level: "advanced",
    category: "Vocabulaire français : niveau avancé",
    categoryKR: "프랑스어 어휘 (고급)",
    instructor: "M. Chagall",
    title: "=",
    summary: "=",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
  {
    id: 19,
    language: "FR",
    level: "careers",
    category: "TRAVAILLER EN FRANCE - DATA SCIENCE",
    categoryKR: "프랑스 해외취업",
    instructor: "M. Chagall",
    title: "=",
    summary: "=",
    description: "",
    price: 100,
    main: false,
    hot: false,
    discount: false,
    discountCode: "",
    discountRate: 0,
  },
];
export default CourseData;
